"""initial

Revision ID: 40d1d4627854
Revises: 3d169df5318e
Create Date: 2026-03-14 18:40:45.107508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40d1d4627854'
down_revision: Union[str, Sequence[str], None] = '3d169df5318e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('medical_receipts_user_id_fkey'), 'medical_receipts', type_='foreignkey')
    op.drop_table('subscriptions')
    op.drop_table('users')
    op.add_column('medical_receipts', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('medical_receipts', sa.Column('provider', sa.String(length=255), nullable=True))
    op.add_column('medical_receipts', sa.Column('hsa_eligible', sa.Boolean(), nullable=False))
    op.add_column('medical_receipts', sa.Column('reimbursed', sa.Boolean(), nullable=False))
    op.add_column('medical_receipts', sa.Column('image', sa.Text(), nullable=True))
    op.add_column('medical_receipts', sa.Column('thumbnail', sa.Text(), nullable=True))
    op.add_column('medical_receipts', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('medical_receipts', sa.Column('reimbursed_at', sa.DateTime(), nullable=True))
    op.drop_column('medical_receipts', 'user_id')
    op.drop_column('medical_receipts', 'receipt_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_receipts', sa.Column('receipt_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('medical_receipts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('medical_receipts_user_id_fkey'), 'medical_receipts', 'users', ['user_id'], ['id'])
    op.drop_column('medical_receipts', 'reimbursed_at')
    op.drop_column('medical_receipts', 'updated_at')
    op.drop_column('medical_receipts', 'thumbnail')
    op.drop_column('medical_receipts', 'image')
    op.drop_column('medical_receipts', 'reimbursed')
    op.drop_column('medical_receipts', 'hsa_eligible')
    op.drop_column('medical_receipts', 'provider')
    op.drop_column('medical_receipts', 'date')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('subscriptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey'))
    )
    # ### end Alembic commands ###
